config/routes.rb
Photo::Application.routes.draw do

  resources :albums, path: '/gallery/'

  resources :images, path: '/gallery/:album/image', constraints: {album: /[-_a-z\d]+/i}, only: [:new, :create, :delete]
  delete '/gallery/:album/:id', to: 'images#destroy', constraints: {album: /[-_a-z\d]+/i}
  #resources :images

  root 'site#index'

  get 'users', to: 'users#index'
  get 'user/:id', to: 'users#show', constraints: {id:/\d+/}
  match 'user/profile', to: 'users#profile', as: 'profile', via: [:get, :patch]
  mount RailsAdmin::Engine => '/administration(.:format)', as: 'rails_admin'

  get '/:action', to: 'site#:action', constraints: {action: /blog|gallery|contact/}
  get '/gallery/:album', to: 'site#gallery', constraints: {album: /[-_a-z\d]+/i}


  devise_for :users, path: 'user', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      registration: ''
  }
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album }
      else
        format.html { render action: 'new' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params[:album]
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= simple_form_for(@album) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<div class="zerogrid">
  <div class="row">
    <div class="main-content">
      <% if @albums.nil? or @albums.empty? %>
          В настоящее время ни одного альбома еще не создано..
      <% else %>

          <% @albums.each do |album| %>
              <article>
                <div class="heading">
                  <h2>
                    <% url = album.album_url.nil? ? album.id : album.album_url %>
                    <%= link_to album.name, create_url('gallery', url) %>
                  </h2>

                  <p class="info">>>> <%= t 'Posted by' %>
                    <b><%= link_to album.user.username, create_url('user', album.user.id) %></b>
                    - <%= album.created_at %> - 0 Comments</p>
                </div>
                <div class="content">
                  <% unless album.image.nil? or album.image.empty? %>
                      <%= image_tag path_to_image(album.image), class: 'album_image', title: album.name, alt: album.name %>
                  <% end %>
                  <p><%= album.description %></p>

                  <p>comments....</p>
                </div>
                <div class="footer">
                  <p class="more"><%= link_to 'Подробнее', create_url('gallery', url), class: 'button' %></p>
                </div>
              </article>
          <% end %>

      <% end %>

      <br>

      <%= link_to 'New Album', create_url(new_album_path) if user_signed_in? %>
    </div>
  </div>
</div>

app/views/albums/new.html.erb
<div class="zerogrid">
  <div class="row">
    <div class="main-content">
      <h1>New album</h1>

      <%= render 'form' %>

      <%= link_to 'Back', albums_path %>
    </div>
  </div>
</div>

app/views/albums/show.html.erb
<div class="zerogrid">
  <div class="row">
    <div class="main-content">

      <%= link_to 'Edit', edit_album_path(@album) %> |
      <%= link_to 'Back', albums_path %>
    </div>
  </div>
</div>