config/routes.rb
Photo::Application.routes.draw do

  resources :albums, path: '/gallery/'

  resources :images, path: '/gallery/:album/image', constraints: {album: /[-_a-z\d]+/i}, only: [:new, :create, :delete]
  delete '/gallery/:album/:id', to: 'images#destroy', constraints: {album: /[-_a-z\d]+/i}
  #resources :images

  root 'site#index'

  get 'users', to: 'users#index'
  get 'user/:id', to: 'users#show', constraints: {id:/\d+/}
  match 'user/profile', to: 'users#profile', as: 'profile', via: [:get, :patch]
  mount RailsAdmin::Engine => '/administration(.:format)', as: 'rails_admin'

  get '/:action', to: 'site#:action', constraints: {action: /blog|gallery|contact/}
  get '/gallery/:album', to: 'site#gallery', constraints: {album: /[-_a-z\d]+/i}


  devise_for :users, path: 'user', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      registration: ''
  }
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
  end

  def gallery
    if params[:album].present?
      @album = Album.find_by_id_and_status(params[:album], true) || Album.find_by_album_url_and_status(params[:album], true)
      @photos = Image.order(id: :desc).find_all_by_album_id_and_status(@album.id, true)
    else
      @albums = Album.find_all_by_status true
    end
  end

  def blog
  end

  def contact
    authorize! :contact, @user unless user_signed_in?
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/about.html.erb
<h1>Site#about</h1>
<p>Find me in app/views/site/about.html.erb</p>

app/views/site/blog.html.erb
<div class="zerogrid">
  <div class="row">
    <div class="main-content">
      <div class="row">
        <div class="col-2-3">
          <article>
            <div class="heading">
              <h2><a href="single.html">Sed vestibulum dui et tellus congue molestie.</a></h2>
              <p class="info">>>> Posted by Admin - 01/01/2012 - 0 Comments</p>
            </div>
            <div class="content">
              <img src="images/img1.jpg"/>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
              <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>
            </div>
            <div class="footer">
              <p class="more"><a class="button" href="single.html">Read more >></a></p>
            </div>
          </article>
          <article>
            <div class="heading">
              <h2><a href="single.html">Nunc quis dui ipsum, eu egestas purus.</a></h2>
              <p class="info">>>> Posted by Admin - 01/01/2012 - 0 Comments</p>
            </div>
            <div class="content">
              <img src="images/img2.jpg"/>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
              <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>
            </div>
            <div class="footer">
              <p class="more"><a class="button" href="single.html">Read more >></a></p>
            </div>
          </article>
          <article>
            <div class="heading">
              <h2><a href="single.html">Sed vestibulum dui et tellus congue molestie.</a></h2>
              <p class="info">>>> Posted by Admin - 01/01/2012 - 0 Comments</p>
            </div>
            <div class="content">
              <img src="images/img3.jpg"/>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
              <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>
            </div>
            <div class="footer">
              <p class="more"><a class="button" href="single.html">Read more >></a></p>
            </div>
          </article>
        </div>
        <div class="sidebar col-1-3">
          <section>
            <div class="heading">About us</div>
            <div class="content">
              Free Basic Html5 Templates created by <a href="http://www.zerotheme.com">Zerotheme</a>. You can use and modify the template for both personal and commercial use. You must keep all copyright information and credit links in the template and associated files.
            </div>
          </section>
          <section>
            <div class="heading">Categories</div>
            <div class="content">
              <ul>
                <li><a href="http://www.zerotheme.com">Free Html5 Templates</a></li>
                <li><a href="http://www.zerotheme.com">Free Css3 Templates</a></li>
                <li><a href="http://www.zerotheme.com">Free Responsive Html5 Templates</a></li>
                <li><a href="http://www.zerotheme.com">Free Basic Html5 Templates</a></li>
                <li><a href="http://www.zerotheme.com">Free Layout Html5 Templates</a></li>
              </ul>
            </div>
          </section>
          <section>
            <div class="heading">Flickr Photos</div>
            <div class="content">
              <table border="0px">
                <tr>
                  <td><img src="images/f1.jpg"/></td>
                  <td><img src="images/f2.jpg"/></td>
                  <td><img src="images/f3.jpg"/></td>
                </tr>
                <tr>
                  <td><img src="images/f4.jpg"/></td>
                  <td><img src="images/f5.jpg"/></td>
                  <td><img src="images/f6.jpg"/></td>
                </tr>
              </table>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/site/contact.html.erb
<div class="zerogrid">
  <div class="row">
    <div class="main-content" style="width:650px;margin: 10px auto">
      <div style="display: inline-block">
        <br><br>
       Email: <%= mail_to 'anna-salnikova87@mail.ru' %>
       <br>
       <br>
       VKontakte: <%= link_to 'vk.com/annasalnikova', 'http://vk.com/annasalnikova', target: '_blank' %>
       <br>
       <br>
       Сайт: <%= link_to 'Фото для друзей', root_path %>
      </div>
      <div style="display: inline-block;float: right">
        <%= image_tag path_to_image('avatar.png'), width: '300px' %>
      </div>
    </div>
  </div>
</div>

app/views/site/gallery.html.erb
<div class="zerogrid">
  <div class="row">
    <div class="main-content">

      <% if @photos.nil? %>



      <% else %>

          <% if @photos.empty? %>
              В настоящее время в данный альбом еще не были загружены фотографии..
          <% else %>

              <% @photos.each do |photo| %>
                  <div class="col04" style="text-align:center;">
                    <% unless photo.image.nil? %>
                        <%= link_to "#{photo.image}", rel: 'prettyPhoto[gallery]' do %>
                            <%= image_tag path_to_image(photo.image), class: 'photo_image', title: photo.name, alt: photo.name %>
                        <% end %>
                        <%= link_to t('Destroy'), create_url('gallery', photo.album.album_url, photo.id), method: :delete, data: {confirm: t('Are you sure?')}, class: 'link' %>
                        <% if false #photo.comments.present? %>
                            <p>
                              #comments..
                            </p>
                        <% end %>
                    <% end %>

                  </div>
              <% end %>

          <% end %>

          <% if @album.user == current_user %>
              <div class="clearfix"></div>
              <hr>
              <%= link_to t('upload_image'), new_image_path %>
          <% end %>

      <% end %>

    </div>
  </div>
</div>

app/views/site/index.html.erb
<!--------------Slideshow--------------->

<section class="featured">
  <div class="rslides_container">
    <ul class="rslides" id="slider">
      <li><%= image_tag path_to_image('portfolio/1.jpg') %></li>
      <li><%= image_tag path_to_image('portfolio/2.jpg') %></li>
      <li><%= image_tag path_to_image('portfolio/3.jpg') %></li>
      <li><%= image_tag path_to_image('slide1.png') %></li>
      <li><%= image_tag path_to_image('slide2.png') %></li>
      <li><%= image_tag path_to_image('slide3.png') %></li>
    </ul>
  </div>
</section>

<!--------------Content--------------->
<section id="content">
  <div class="zerogrid">
    <div class="row">
      <div class="main-content">
        <div class="row">
          <div class="col-1-3">
            <section>
              <div class="heading">
                <h2><a href="blog.html">Our Company</a></h2>
              </div>
              <div class="content">
                <%= image_tag path_to_image('icon1.jpg') %>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
              </div>
            </section>
          </div>
          <div class="col-1-3">
            <section>
              <div class="heading">
                <h2><a href="blog.html">Projects</a></h2>
              </div>
              <div class="content">
                <%= image_tag path_to_image('icon2.jpg') %>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
              </div>
            </section>
          </div>
          <div class="col-1-3">
            <section>
              <div class="heading">
                <h2><a href="blog.html">Information</a></h2>
              </div>
              <div class="content">
                <%= image_tag path_to_image('icon3.jpg') %>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>