config/routes.rb
Photo::Application.routes.draw do

  resources :albums, path: '/gallery/'

  resources :images, path: '/gallery/:album/image', constraints: {album: /[-_a-z\d]+/i}, only: [:new, :create, :delete]
  delete '/gallery/:album/:id', to: 'images#destroy', constraints: {album: /[-_a-z\d]+/i}
  #resources :images

  root 'site#index'

  get 'users', to: 'users#index'
  get 'user/:id', to: 'users#show', constraints: {id:/\d+/}
  match 'user/profile', to: 'users#profile', as: 'profile', via: [:get, :patch]
  mount RailsAdmin::Engine => '/administration(.:format)', as: 'rails_admin'

  get '/:action', to: 'site#:action', constraints: {action: /blog|gallery|contact/}
  get '/gallery/:album', to: 'site#gallery', constraints: {album: /[-_a-z\d]+/i}


  devise_for :users, path: 'user', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      registration: ''
  }
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :album
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @album = Album.find_by_id_and_status(params[:album], true) || Album.find_by_album_url_and_status(params[:album], true)
    not_found and return if @album.blank? or !user_signed_in?
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @album = Album.find_by_id_and_status(params[:album], true) || Album.find_by_album_url_and_status(params[:album], true)
    not_found and return if @album.blank? or !user_signed_in?
    @image = Image.new(image_params)
    @image.user_id = current_user.id
    @image.album_id = @album.id

    respond_to do |format|
      if @image.save
        format.html { redirect_to "/gallery/#{@album.album_url}", notice: 'Image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @image }
      else
        format.html { render action: 'new' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to images_url(@image), notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    url = @image.album.album_url
    @image.destroy
    respond_to do |format|
      format.html { redirect_to "/gallery/#{url}", notice: 'Image was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit :image, :name, :description
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= simple_form_for(@image) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.file_field :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<div class="zerogrid">
  <div class="row">
    <div class="main-content">
      <h1>Listing images</h1>

      <table>
        <thead>
        <tr>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @images.each do |image| %>
            <tr>
              <td><%= link_to t('Show'), create_url(path_to_image image)%></td>
              <td><%= link_to t('Edit'), create_url(edit_image_path image) %></td>
              <td><%= link_to t('Destroy'), image, method: :delete, data: {confirm: t('Are you sure?')} %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to t('upload_image'), create_url(new_path_to_image) %>
    </div>
  </div>
</div>

app/views/images/new.html.erb
<div class="zerogrid">
  <div class="row">
    <div class="main-content">
      <h1><%= t 'new_image'%></h1>

      <%= render 'form' %>

      <%= link_to 'Back', images_path %>
    </div>
  </div>
</div>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_path_to_image(@image) %> |
<%= link_to 'Back', images_path %>